### ISSUE TITLE
301 redirects to 404

### ISSUE THREAD

**Issue by shellscape** [pypi/warehouse#10916]
**Describe the bug**

_I'm not entirely sure if this is a bug, but it appears to be on the surface. There may be some institutional reason for this behavior, but I was unable to dig it up while searching around._

Packages which no longer exist within the pypi registry are being served with a 301 response (Permanently Moved), which then redirects to a 404 page. For example: https://pypi.org/project/django-flattr/json

I believe that this is technically incorrect, as the resource hasn't been moved - it no longer exists. 

**Expected behavior**

I was expecting a 404 right on the outset. 

**To Reproduce**

`curl https://pypi.org/project/django-flattr/json`

**My Platform**
Any HTTP request tool or browser will do the job.

**Additional context**

**Comment by di** [comment]
Thanks for the issue! The URL is wrong and should be `https://pypi.org/project/django-flattr/json/`. Since we issue a _lot_ of these redirects which add the trailing slash, we do it at the CDN-level, before it hits our web backends and thus before we are able to determine if the project exists or not.

I don't think it's likely that we'll change this, but perhaps you can tell us why it's a problem for you so we can triage accordingly.
