### ISSUE TITLE
Support migration of user to organization

### ISSUE THREAD

**Issue by stephenfin** [pypi/warehouse#11811]
**What's the problem this feature will solve?**

It appears that work to add support for organizations in PyPI [is finally underway](https://github.com/pypi/warehouse/issues/201#issuecomment-1180240313). I've looked through [the project dashboard](https://github.com/orgs/pypi/projects/1) and failed to spot anything akin to $subject. Given the long-term lack of support for organizations, many users and groups have invented their own way to share ownership of packages within a community. In some cases, this involved the creation of a "bot" user account whose credentials are known to CI (which is in turn responsible for creating releases). For example, [the `openstackci` user](https://pypi.org/user/openstackci/) is the sole "user" responsible for managing all packages from the OpenStack community. I think it would be extremely helpful if there was a mechanism to migrate such users to organizations, thus avoiding the need to create a new organization and manually migrate all packages to this.

**Describe the solution you'd like**

Add a mechanism to migrate a user to an organization. This could either be a web UI "wizard" or a page in the docs asking users to email PyPI admins (who would do this for them). If we did it via a web UI wizard then the user initiating the migration would need the ability to specify the new owner(s) of this organization (in the case of `openstackci`, this would be the OpenInfra sysadmins).

**Additional context**

**Comment by ewdurbin** [comment]
We are not going to support his at this time. Primarily due to the fact that we will have separate namespaces for User and Organization objects. As such, we can't necessarily guarantee that a given username is available as an Organization slug.

We will take into account usernames when reviewing requests for new Organizations, but will not have tooling to support bulk migration of projects between the two initially. Once Organization features have launched, we'll address bulk migration of Project ownership between Users and Organizations if there is a desire.

That could be captured in a new issue now, if you want to file it.
