### ISSUE TITLE
Rename "Critical" to "Popular"

### ISSUE THREAD

**Issue by dstufft** [pypi/warehouse#11823]
This is just a random idea, but a non-trivial number of people have concerns over the use of the word "critical" and what that implies about their project.

There's already emails and campaigns going out using the word critical, so it may not be worth changing now, but we may want to consider switching to a term that may have less connotations. "Popular" could be useful here, since (most) of these projects are included by nature of their download counts.

Maybe it's fine though, I dunno. Just throwing it out there.

**Comment by njsmith** [comment]
"Popular" was my first thought too, but then I realized that it could be misunderstood by all the package users who want PyPI to do a better job at curating and telling them which packages to use. Like they might think "Popular" = "Recommended". I guess this would only be an issue if exposing this metadata in the UI, but your second post mentioned that :-)

I guess one strategy would be to start exposing basic download statistics in the UI, since that's a super popular feature request anyway, and then you can point to it and say "2FA is mandated for all projects where that number is greater than this threshold". (Also makes it easier to move the threshold down incrementally over time, if that's the plan.)

**Comment by fitojb** [comment]
From the beginning, I translated “critical” as “crucial” for this very reason.
