### ISSUE TITLE
"Username and/or password are wrong" When entering correct credentials using Maturin

### ISSUE THREAD

**Issue by nednoodlehead** [pypi/warehouse#12133]
**Describe the bug**
Using Maturin (Rust module) to upload to Pypi gives the error: "Username and/or password are wrong", when the credentials are correct. I'm coming from this issue, orignally opened for that Module: https://github.com/PyO3/maturin/issues/999
They are saying the error is from here

**Expected behavior**
I use the "maturin publish" command to upload to Pypi. It should create the module and upload it or whatever. (It does not do this)

**To Reproduce**
1). Write rust module, a quick one to copy is: https://github.com/letsgetrusty/word_counter
2). Open in IDE of choice (For me Pycharm)
3). Go into the IDE terminal (accessing powershell in a venv essentially)
4). Type: maturin publish
5). Enter username & password
6). Error: 
⛔ Username and/or password are wrong
💥 maturin failed
  Caused by: Username and/or password are wrong

**My Platform**

**Additional context**
Again, I'm coming from this issue: https://github.com/PyO3/maturin/issues/999 (Closed as completed by maintainer)
(Which I don't see the original poster made a report)
-My account on Pypi is recently made, and DOES have multi-factor auth & email verification
- I haven't been able to get the package to work in any environment that isn't a virtual environment (It's own can of worms)
- I entered my password in a few different fashions: Slowly typing 1 by 1, copy & paste, log into site with that password (successful)

**Comment by di** [comment]
The issue here is almost certainly with the client:

* if the file already exists, PyPI will respond with a 400 status code and a body "File already exists". https://github.com/pypi/warehouse/blob/f2d6fc455a135b3b3ba72539d5c9f4c4f0d48223/warehouse/forklift/legacy.py#L1223-L1231
* if the credentials are incorrect, PyPI will respnod with a 403 status code and a body "Invalid or non-existent authentication information." https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/accounts/security_policy.py#L101-L105

The client should be able to distinguish between these two responses.

**Comment by nednoodlehead** [comment]
Solved. Created new account with a different password. I won't gaslight myself into thinking that I typed the password wrong 20+ times.
Broken account I guess

**Comment by DilecPadovani** [comment]
> Solved. Created new account with a different password. I won't gaslight myself into thinking that I typed the password wrong 20+ times. Broken account I guess

How did you solve the issue? I get this error using password or the token: 
``` bash
🚀 Uploading 1 packages
⛔ Username and/or password are wrong
💥 maturin failed
  Caused by: Username and/or password are wrong

```

**Comment by marki259** [comment]
Same issue here

**Comment by henselman-petrusek** [comment]
Same issue here. To be explicit, the solution was:

(1) create an API token on PyPI
(2) when prompted, enter `__token__` as the username and the API token as the password.

**Comment by di** [comment]
PyPI no longer supports uploading with username/password authentication since our mandatory 2FA policy went into effect: https://blog.pypi.org/posts/2023-12-13-2fa-enforcement/

Similar to the original issue, Maturin seems unable to distinguish between the different types of authentication failures PyPI may produce here.
