### ISSUE TITLE
Allow claiming a "too-similar" package name

### ISSUE THREAD

**Issue by smurfix** [pypi/warehouse#12178]
**What's the problem this feature will solve?**

Sometimes names are intentionally similar. For instance, I have an "asyncdbus" package, which obviously affects async access to dbus. Now I want to post a package "asyncmodbus" which does the same thing for modbus, which has nothing to do with dbus. However both modbus and dbus are established buses.

**Describe the solution you'd like**

Add an issue form for claiming a "too-similar" name.

Also, if the packages' maintainer is the same person, let's please presume that they know what they are doing.

**Comment by di** [comment]
We do have a process for this, you can file an issue [here](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME).

In this case, the issue is that `asyncmodbus` is too similar to https://pypi.org/project/async-modbus/, not `asyncdbus`
