### ISSUE TITLE
Repurpose 'malware' checks / YARA scanning for secret scanning

### ISSUE THREAD

**Issue by di** [pypi/warehouse#12412]
**What's the problem this feature will solve?**
While our existing 'malware' checks are not being used due to noise and false positives, the mechanics available via the checks are perfect for token/credential scanning.

**Describe the solution you'd like**
We should be able to write a class of checks that:
- scans every file in a distribution for a given pattern
- calls an internal/external webhook with the result, in some specified format

Once this is implemented, we should support scanning for specific tokens:
- [ ] `pypi-` and `testpypi-` prefixed tokens, which should automatically be revoked when found
- [ ] 'reciprocal' scanning for GitHub tokens: https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
- [ ] other platforms/ecosystems?

**Additional context**
Some other potential ecosystems that might want to integrate: https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns

**Comment by di** [comment]
Related: https://tomforb.es/i-scanned-every-package-on-pypi-and-found-57-live-aws-keys/

**Comment by orf** [comment]
I think there is limited value in rolling our own secret scanning solution for PyPi. We could of course scan for specific patterns we derive ourselves (like I did for AWS keys) and work out how to validate each one, but this is really re-implementing the Github secret scanning infrastructure. Which already has a _lot_ of partners: https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns

I've been toying with a stupid sounding idea that I can't seem to let go of. Why don't we extract all text files from each uploaded release and commit them to a unique orphaned branch in a Github repository? We could expire the branches after a period of time, to keep the repo size down, and I expect the total size of all unique text content in pypi is _significantly_ lower than the 12tb total storage size.

This would trigger a scan against all supported providers, without us needing to really do much.

**Comment by orf** [comment]
I've started work on committing the text content of every file uploaded to PyPi in November 2022, with the aim of seeing how many secrets Github would detect. It's being added here: https://github.com/orf/pypi-import

I think we've massively underestimated the number and variety of credentials that have been published to PyPi. It has only complete about 15% of December, but it's already found hundreds of keys from many different services. Spot checking them reveals even more, including just [straight up, valid, raw database credentials](https://github.com/orf/pypi-import/blob/2d421ba607f8fe5146dc5f3cdfda26f25a2110de/output/test_sf_etl_py3-0.0.2.tar.gz#L392).

**Comment by orf** [comment]
I finally got around to finishing the side project I mentioned above, and the results are quite scary.

I began mirroring uploads to Github (for example [this repo](https://github.com/pypi-data/pypi-mirror-227/tree/code/packages) contains code uploaded to PyPI between 2023-08-24 and 2023-08-29), with the intention to both allow easier analysis of the code and leverage Github's existing secrets scanning infrastructure.

In #13647 it was said by @ewdurbin: 

> I propose https://github.com/pypi/warehouse/pull/13596 combined with some form of "what's new!" feed to build out a more generic interface for internal and external "third parties" to perform these kinds of scans and report them to PyPI.

This sounds like a great idea and I know gitguardian.com is interested in this. They support a wider range of credential types than Github and I've been working with them to scan the all the historic code. Both the volume and types of credentials that are present are very scary and a non-trivial portion of them are live + valid.

The [stats page on the project website](https://py-code.org/stats) details the high-level breakdown of secrets detected by Github:

<img width="1411" alt="Screenshot 2023-09-06 at 10 28 32" src="https://github.com/pypi/warehouse/assets/1027207/73cc3371-e754-46da-b475-84123d5ee270">

And this analyis using the data from GitGuardian on only _valid_ credentials (i.e ones their service is able to detect as valid) shows the number of individual projects with valid credentials published is growing over time:

<img width="621" alt="Screenshot 2023-09-06 at 10 30 26" src="https://github.com/pypi/warehouse/assets/1027207/f6562a20-6237-4ba3-9089-4264369950c9">

However the issue is both detection _and_ remediation. It's OK to get an alert from PyPI saying there's some credentials in your release, but unless you see and/or action that then you're in for a bad time.

The part that (unfortunately) benefits from centralization here is notifying the _providers_ as well. For example, when an AWS key is added to Github AWS will be pinged and will:
1. Apply a "quarantine policy" to the key to prevent obviously destructive/expensive operations
2. Email the account holder and the user associated with the key

Other providers do similar things. This part is tough to crack unless Github themselves allow limited third parties to use this portion of their secrets scanning infrastructure without necesseraly comitting code to Github.

**Comment by orf** [comment]
Here is a breakdown of all the _live_ and valid credential types found:

<details>
  <summary>Credentials</summary>

- AMQP Credentials
- Dropbox Key
- GitLab Token
- Airtable API Key
- Line Token
- Facebook App Keys
- Pushbullet API key
- Pusher Channels Keys
- Coveralls Repository Token
- Clarifai Key
- reCAPTCHA Key
- New Relic API Key
- Datadog API Credentials
- Zoom API JWT Keys
- FTP Credentials
- Twilio Master Credentials
- Dropbox App Credentials
- Hunter API Key
- Telegram Bot Token
- Clearbit Key
- Mapbox Token
- Cloudflare API Credentials
- Coveralls Personal Token
- CircleCI Personal Token
- IBM Cloud Key
- Yelp API key
- Alchemy API Key
- Trello Keys
- Shodan Key
- PayPal OAuth2 Keys
- DigitalOcean Token
- Yousign API Key
- Auth0 Keys
- Google API Key
- New Relic Key
- IBM COS HMAC Credentials
- Cloudinary API keys
- Sentry Token
- GitHub OAuth App Keys
- AWS Keys
- Algolia Keys
- PubNub Publish and Subscription Keys
- Mailgun Primary Key
- Stripe Keys
- MySQL Credentials
- Redis Credentials
- MongoDB Credentials
- Coinbase Keys
- PagerDuty Authorization Token
- Firebase Cloud Messaging API Key
- Pinecone API Key and environment
- Twitter Access Keys
- Etsy Developer Key
- WeChat App Keys
- Stream Keys
- Discord Webhook URL
- Notion Integration Token
- OpenWeatherMap Token
- Mailjet Keys
- GitHub App Keys
- AWS SES Keys
- PostgreSQL Credentials
- Spotify Keys
- SSH Credentials
- SparkPost Key
- Riot Games API Key
- Azure Active Directory API Keys
- Discord Oauth2 Keys
- Codacy API Credentials
- Google Cloud Keys
- Tencent Cloud Keys

</details>

Azure Active Directory API Keys are a bit scary.
