### ISSUE TITLE
Show if package contains py.typed

### ISSUE THREAD

**Issue by JakobDev** [pypi/warehouse#12614]
According to [PEP 561](https://peps.python.org/pep-0561/#packaging-type-information), package maintainers can add a py.typed file to their package. If that file exists, it means the package contains type annotations and can be used with external stubs with static type checkers. For people for care about this, it would be nice to show in the Web UI if a package has such a file.

**Comment by miketheman** [comment]
Hi @JakobDev ! 
Today the warehouse supports Classifiers from Metadata per https://peps.python.org/pep-0301/ - and these are displayed in the UI on the sidebar:

<img width="348" alt="Screenshot 2022-12-06 at 12 27 32" src="https://user-images.githubusercontent.com/529516/205980733-785b9eea-ccd2-4e6e-80a3-7d7ac6c8a11a.png">

Users can also filter searches by this classifier:
<img width="237" alt="Screenshot 2022-12-06 at 12 28 53" src="https://user-images.githubusercontent.com/529516/205980957-188d4693-0545-454e-905d-1f9a3668a802.png">

If you've found libraries that don't have this metadata, I'd encourage adding that to their metadata so it becomes part of the existing behaviors!

**Comment by dstufft** [comment]
I'm going to close this for three reasons:

- We already provide a way for packages to express that they're typed via the classifiers that @miketheman linked.
- It's difficult to do this in a way that isn't going to be prone to odd failures and false positives and false negatives.
- It's not clear that it actually makes sense to surface that information for every package. 

One problem is that in an sdist we don't really have any idea *what* is going to be installed, or if the files that are going to be installed even exist in the sdist (for instance, you could imagine a sdist that just writes out a `py.typed`). We could just scan for any `py.typed`, but that may be projects that aren't going to be installed, or buried deep in some tree for vendored packages.

We could look inside of wheels to determine this information, since we know what is going to be installed in those cases, but then we have the problem of what happens if different wheels disagree on whether or not a `py.typed` is going to be installed or not.

Also peeking inside of the package is something we can do (and we're starting to do it for PEP 658), but I think we would be loathe to add more things that we have to attempt to extract out of the artifacts unless it was something that was providing great benefit.

But finally, I think that ultimately authors are in control over their projects metadata, and we should avoid trying to guess at what they meant, and provide them the tools to declare it and surface that information for them. If the classifier isn't sufficient, then maybe we need better metadata for this case (I suspect it *is* sufficient though), but ultimately I think the author should be in control over whether or not their package is declared to be typed or not.
