### ISSUE TITLE
Prefilled password not detected in API token removal UI

### ISSUE THREAD

**Issue by PeterJCLaw** [pypi/warehouse#12766]
**Describe the bug**

When removing an API token the popup UI asks for your password, with the "Remove API token" button initially disabled. If the password field is pre-filled by a password manager then the "Remove API token" button remains disabled even though the password field has the correct content present.

**Expected behavior**

The UI should detect that a password manager may have already filled in the field content when it is shown.

**My Platform**

Firefox 108.0.1 (64-bit snap) on Ubuntu 22.04 LTS.
Using the Firefox password manager.

**Comment by miketheman** [comment]
I can confirm the behavior on Firefox using the Firefox password manager does not work -- using 1Password works -- so there's likely a difference in the JS Events behavior between the two. 

As a workaround, you can cancel the modal and reopen it, the prompt to insert a password should work and activate the button, like so:

https://user-images.githubusercontent.com/529516/211359446-3b22f095-aebd-4704-81b2-60e49adc5b4a.mov

Not a solution, but I'll continue poking at it.

**Comment by miketheman** [comment]
Since Chrome does not auto-fill the saved password value until prompted, this is only applicable to Firefox so far.

The behavior is driven by the Firefox default setting `Autofill logins and passwords` - disabling this allows the user to auto-fill on focus successfully.

After continuing to dig, I _think_ this is due to how Firefox Password Manager populates - it appears to pre-fill the applicable `input` fields in HTML, possibly even before the JS handlers have started up. I haven't been able to find useful details on debugging Firefox's internal behaviors or finding what events are emitted.

The modal is hidden in the HTML, and is unhidden when clicking the option.
Adding a check to the controller to run `check()` when it connects might solve this issue.

**Comment by PeterJCLaw** [comment]
Nice, thanks for the speedy fix! :racing_car:
