### ISSUE TITLE
Remove walletconnect package

### ISSUE THREAD

**Issue by bitlogik** [pypi/warehouse#12894]
Some blank project should be removed.
For example : https://pypi.org/project/walletconnect/

This is a kind of a placeholder, which looks like more to be present for SEO purpose.
It tricks the users this is a real package, but this is empty for 18 months. It pollutes the real work from real companies.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

If you believe this project is malicious, please see https://pypi.org/security/, otherwise if you think this project is invalid and would like to claim the name, see https://pypi.org/help/#project-name-claim.
