### ISSUE TITLE
400 Bad CSRF Token when trying to log from macOS Safari

### ISSUE THREAD

**Issue by laclouis5** [pypi/warehouse#13156]
**Describe the bug**
The following error is returned when trying to log from macOS (13.2.1) Safari (16.3). There is no issue when using Firefox or uploading a dist with Twine.

```
400 Bad CSRF Token
Access is denied. This server can not verify that your cross-site request forgery token belongs to your login session. Either you supplied the wrong cross-site request forgery token or your session no longer exists. This may be due to session timeout or because browser is not supplying the credentials required, as can happen when the browser has cookies turned off.

check_csrf_token(): Invalid token
```

**Expected behavior**
Succesful log in.

**My Platform**
MacBookPro 14" M1 Pro (2021)
macOS Ventura 13.2.1
Safari 16.3 (18614.4.6.1.6)
Using iCloud Private Relay

**Comment by ewdurbin** [comment]
I'm able to immediately reproduce this by setting the "Block all cookies" setting in "Settings > Block all cookies", can you check the value of that setting?

As the error message suggests: `... as can happen when the browser has cookies turned off.`, and as the setting warns when being toggled on `Websites may not work if you do this. Are you sure you want to block all cookies?` this is expected behavior in that case.

**Comment by laclouis5** [comment]
I checked and the option is not enabled.

**Comment by laclouis5** [comment]
This is weird, I did not changed anything in the meantime and it now works properly. I tried to log in and I was already logged in.

**Comment by miketheman** [comment]
@laclouis5 Thanks for following up and glad it's now successful.
Going to close for now, but in the event this happens again, please reopen with any more details we would need to reproduce.
