### ISSUE TITLE
URL to trusted publisher workflow is confusing

### ISSUE THREAD

**Issue by di** [pypi/warehouse#13463]
As discussed [here](https://twitter.com/HEPfeickert/status/1649181900521472001), the URL in the list of trusted publishers is a little confusing to users because it links to a workflow on a specific branch (`HEAD`) where in reality any matching workflow on any branch in the repository can publish.

Instead of a full URL to the workflow, we should display the name of the org/repo (with a link) and the filename of the workflow (without a link).

**Comment by di** [comment]
> I'm not sure I understand the comment - how does a SHA get embedded, and how might it be used?

I'm not sure I understand the comment either: @woodruffw, any thoughts?

> Otherwise we'd have to construct some other string for this purpose, since we preserve the publisher_url in Events (unless we don't care about the HEAD aspect there either?)

We should probably update this to be the _actual_ URL to the workflow that _actually_ published the file (which we can construct from the OIDC claims) which will likely include the SHA, which might be what @woodruffw was talking about in that comment.

**Comment by woodruffw** [comment]
> I'm not sure I understand the comment either: @woodruffw, any thoughts?

Yeah, that's a misleading comment on my part: that was referring to somehow embedding the OIDC token's `ref` claim in various publisher management events, but that's currently not possible due to how we disconnect the state during token exchange.

> Otherwise we'd have to construct some other string for this purpose, since we preserve the publisher_url in Events (unless we don't care about the HEAD aspect there either?)

Correct, this is what the comment was referring to. IMO it'd be fine to remove the `publisher_url` from both, and replace both with individual fields for the components.
