### ISSUE TITLE
Trusted publishing: new GitHub action to mint an API Token

### ISSUE THREAD

**Issue by tschm** [pypi/warehouse#13555]
Thank you for making trusted publishing a reality. 

We took your manual path and put it into a new Gitlab action, see
https://github.com/marketplace/actions/pypi-token-mint

It is hence possible to combine trusted publishing with poetry, etc.

**Comment by woodruffw** [comment]
Thanks for the announcement @tschm!

I can understand the desire to have a dedicated API token minting action, but the official recommendation at the moment is to use the PyPA's [integrated publishing action](https://github.com/pypa/gh-action-pypi-publish), along with PyPA-maintained publishing tools like [twine](https://github.com/pypa/twine). These tools are developed in tandem with Warehouse (particularly around parts of PyPI that are not well standardized, like the upload endpoint). 

Given that, I think it's _currently_ inadvisable to link between Warehouse's docs and these actions -- it'll likely produce confusion around what PyPI's support and stability guarantees are, as well as around how we encourage users to use the "trusted publishing" functionality.

On a related note: it looks like your action is licensed under Apache-2.0, which is fantastic! Please don't forget to add a corresponding attribution for the Warehouse authors, since both the `README.md` and the `action.yml` itself appear to be partially derived from code and documentation in this repository 🙂

**Comment by tschm** [comment]
Interesting, what's the position on poetry publish which is **not** using twine? The Github action above is just cleaning up your manual approach which is helpful and interesting to understand the overall process. It does a lot less than the official PyPA action but also gets away with a tiny action.yml script rather than a Docker image that is constructed. However, the complexity remains in poetry publish.
