### ISSUE TITLE
Suddenly unable to parse README.rst, which was functioning correctly when the library version was uploaded.

### ISSUE THREAD

**Issue by mscisdk** [pypi/warehouse#14064]
**Describe the bug**

Project description is showing README.rst raw file.
Earlier it was correctly displaying the rendered content.
This was working fine since the library was uploaded on 20th June 2023 but suddenly stopped working starting this week.

**Expected behavior**

Project description should be visible correctly by parsing README.rst.

**To Reproduce**

Got to library https://pypi.org/project/msci.sdk/ and check project description on landing page.

**My Platform**

**Additional context**

**Comment by di** [comment]
Your release file is missing the [`Description-Content-Type`](https://packaging.python.org/en/latest/specifications/core-metadata/#description-content-type) metadata field:

https://inspector.pypi.io/project/msci-sdk/1.0.0/packages/84/47/7d00a00892dc44b2e61189a79b3e08c42501692c9fe6b171bdc462b8690f/msci.sdk-1.0.0-py3-none-any.whl/msci.sdk-1.0.0.dist-info/METADATA

Without seeing the source you built this from, it's hard to determine why this isn't present, but it may be because you're using older versions of tools to build your package. If you can you give me a link to a source repository for this, or tell us how you built it, we can potentially help debug further.

**Comment by di** [comment]
I can tell that this was built with [`wheel==0.37.1`)[https://inspector.pypi.io/project/msci-sdk/1.0.0/packages/84/47/7d00a00892dc44b2e61189a79b3e08c42501692c9fe6b171bdc462b8690f/msci.sdk-1.0.0-py3-none-any.whl/msci.sdk-1.0.0.dist-info/WHEEL#line.2] which is from [late 2021](https://pypi.org/project/wheel/0.37.1/), you might want to try upgrading that in your build environment.

**Comment by mscisdk** [comment]
@di, we managed to resolve the rendering issue by releasing a new minor version, which involved adding the "long_description_content_type" and upgrading the wheel version.
You can find the fixed version at https://pypi.org/project/msci.sdk/1.0.1/.

Regarding the older version at https://pypi.org/project/msci.sdk/1.0.0/, is there any way to somehow address the rendering issue?

In addition, we tried uploading a version on testpypi using the same source code as the 1.0.0 version, without including the "long_description_content_type" and the old wheel. 
Surprisingly, it parsed correctly, and you can access it at https://test.pypi.org/project/msci.sdk/1.0.0rc2/.
Could you please provide clarification on this?

**Comment by miketheman** [comment]
Took me a while, but I finally found where the bug was introduced: [`4a62ac7` (#13219)](https://github.com/pypi/warehouse/pull/13219/commits/4a62ac7db184899272a5240f314dc52ca405c2da#diff-e4b0b47c24cd6c43adee9d281fbe897e55d45aebb988a7c081ba896bdf361ec2R35-R40)

During the refactor to no longer use methods from deprecated `cgi` stdlib, the behavior changed from returning either a valid `content_type or ""` to the output of `msg.get_content_type()`, which changes the `None` into `text/plain`.

**Comment by miketheman** [comment]
> Regarding the older version at [pypi.org/project/msci.sdk/1.0.0](https://pypi.org/project/msci.sdk/1.0.0/), is there any way to somehow address the rendering issue?

Now that a fix has been shipped for new uploads, and an admin page feature to rerender the page with the fix, I've ran a re-render of the 1.0.0 version, and it **renders** correctly. Once the cache expires, it'll **display** correctly as well - about 24 hours.

Sorry for the disruption!
