### ISSUE TITLE
Warn about API key usage/presence when Trusted Publishing is configured

### ISSUE THREAD

**Issue by di** [pypi/warehouse#14171]
Currently in our Trusted Publishing flow, we don't direct the user to remove/delete API tokens that were previously being used for pushing, potentially leading to the long-lived tokens remaining available for publishing.

As a result, we should do the following:
- We should warn (via email) whenever an API key is used for a project where Trusted Publishing is configured, suggesting that the maintainer remove the API token.
- We should additionally send a one-time or occasional email (every 1 month?) whenever an API token exists for a project where Trusted Publishing is configured, regardless of whether it's been used fr publishing.
- We should update the flow to immediately identify long-lived tokens that are no longer necessary, and prompt the user to remove them.

**Comment by sethmlarson** [comment]
Should we wait until after trusted publishing has succeeded once to email them? I suspect it would be frustrating to get an email immediately if you're evaluating trusted publishers.

**Comment by di** [comment]
Yes, my thought is that the first bullet above would only happen after a publish event with a trusted publisher, and the second would only happen after some period of time after the publisher was configured.

**Comment by ristomcgehee** [comment]
Instead of prompting to remove old API tokens, I think it would be better to have a project setting that disables uploading via API token, as discussed in https://github.com/pypi/warehouse/issues/14300. Removing all API tokens for a project might not be straightforward, because a user is not able to see a list of outstanding tokens that are scoped to a project since there might be tokens that belong to other users. There also might be tokens scoped to all projects for a user, and some of those projects might not be set up to use Trusted Publishing.

It could still be worthwhile sending an email when an API token is used if Trusted Publishing is enabled, and also if API tokens exist and the project has not disabled publishing with API tokens.

What do y'all think?

**Comment by woodruffw** [comment]
Triaging: @facutuesca and I will be working on this next!

> * We should warn (via email) whenever an API key is used for a project where Trusted Publishing is configured, suggesting that the maintainer remove the API token.

This sounds good to me! We might want to cap this on "once per release," to avoid sending N emails for N files uploaded at a time.

> Should we wait until after trusted publishing has succeeded once to email them? I suspect it would be frustrating to get an email immediately if you're evaluating trusted publishers.

Yeah, this makes sense to me -- there's a `Release.trusted_published` property that we could key on for this.

To summarize, I think we can do this in two parts:

- [ ] Email notifications, both on release creation and periodically (30 days to start)
- [ ] Form/flow changes, including adding a button/link for users to click to bulk remove any "equivalent" scoped API tokens

If that sounds reasonable to you @di, we'll get started on those 🙂

**Comment by di** [comment]
We might want to put a field on the publisher itself to determine if it's been used or not -- I suspect that would be helpful to identify publishers that were created but never used and might need to be removed.

Otherwise, that all sounds reasonable to me!

**Comment by woodruffw** [comment]
Whoops, another thing that @facutuesca and I talked about: in addition to email notifications/flow changes, another thing that PyPI could do here is return an informational message in the successful token exchange. The GitHub Action (or other consuming clients) could then pick that up and render it, similar to how `twine` will render an informational message from the receiving index.

One downside there is that the message will potentially be "overscoped," i.e. we'll send it to any workflow that does Trusted Publishing, when the people viewing it may not necessarily have permissions to take actions on it (they might be project maintainers but not owners on PyPI, and can't delete existing tokens). So this might not be immediately valuable, but I figured I'd flag it here as well 🙂

**Comment by di** [comment]
I would expect that if the workflow is otherwise successful, the likelihood of the message ever being seen is low, so that might not be worth our effort.

**Comment by facutuesca** [comment]
I have some questions to confirm if I'm understanding correctly:
1. For the 30-day periodic email, who do we want to email? The owner of the project or the owner of the API token? I imagine it's the owner of the token since they are the ones who can take the recommended action (delete the token)

2. Also, we only care about API tokens scoped only for that single project, correct? Or do we also want to warn about API tokens scoped for all the user's projects?

3. Finally, for the 30-day periodic email, how do we gather the users who should receive the email? Do we want to iterate over all projects, filter those with a trusted publisher, get their users (owners & maintainers), and then filter those with macaroons scoped to that single project? I'm not sure what's the most efficient way of doing this.

**Comment by woodruffw** [comment]
> 1. For the 30-day periodic email, who do we want to email? The owner of the project or the owner of the API token? I imagine it's the owner of the token since they are the ones who can take the recommended action (delete the token)

Yep: we want to email the user who can take the action, not other users. Longer term we might want to think about how we can provide all project owners visibility into scoped tokens for their projects, but that has a security dimension that probably needs further thought 🙂


> 2. Also, we only care about API tokens scoped only for that single project, correct? Or do we also want to warn about API tokens scoped for all the user's projects?
> 

Correct!

> 
> 3. Finally, for the 30-day periodic email, how do we gather the users who should receive the email? Do we want to iterate over all projects, filter those with a trusted publisher, get their users (owners & maintainers), and then filter those with macaroons scoped to that single project? I'm not sure what's the most efficient way of doing this.

We might need to play around with this to build a performant query, but that sounds roughly right. We could also bubble it in the opposite direction (select all macaroons that are registered to trusted publishers, extract their project scopes, and select the projects that have owners with corresponding scoped tokens). But I suspect that'll be less efficient.

**Comment by woodruffw** [comment]
> I think this way would contradict #15432, right? If we prune macaroons associated with trusted publishers daily, then the list of all macaroons that are registered to trusted publishers won't be an accurate view of all the active trusted publishers

Ah, yep -- that wouldn't work in the presence of #15432. So let's definitely not do that 🙂

**Comment by di** [comment]
> For the 30-day periodic email, who do we want to email? The owner of the project or the owner of the API token? I imagine it's the owner of the token since they are the ones who can take the recommended action (delete the token)

We definitely want to email the token owner. I think it wouldn't be unreasonable to also email the other project maintainers at the same time, and tell them there is a token owned by <user>. We definitely should email _all_ maintainers when a token is actually used (and probably say by whom).

**Comment by facutuesca** [comment]
Here's the PR for adding the email warnings triggered by a file upload: https://github.com/pypi/warehouse/pull/15453/files

**Comment by di** [comment]
Looking at https://github.com/pypi/warehouse/pull/15453, I'm wondering if this is going to be annoying for users who have a legitimate reason to not do all of their releases via Trusted Publishing (e.g., have some builds on a platform that isn't supported), which might lead to them not wanting to use Trusted Publishing.

I'm thinking we might want this warning to only happen once per API token, as a warning, and not on every usage. This makes things a little more challenging (as we need to maintain state about whether we've warned about a given API token), and makes it a little less likely that the user will take action, but should be a better UX.

**Comment by facutuesca** [comment]
> I'm wondering if this is going to be annoying for users who have a legitimate reason to not do all of their releases via Trusted Publishing (e.g., have some builds on a platform that isn't supported)

What is the usual workflow in these cases? I would have assumed that given a release version (e.g., `1.0.0`), the release would be created by their CI (uploading the files and creating the release on PyPI), and then the user would manually upload the wheels for not-supported platforms under the same (existing) `1.0.0` release version.

In that case, with the current implementation in https://github.com/pypi/warehouse/pull/15453, they would not get a warning since we only warn on API token use during release creation. But the `1.0.0` release is created by their CI (using the Trusted Publisher), so the following file uploads to the same release using the API token should not trigger the email.

Is there another workflow where the release for a project with Trusted Publishing configured is created first by the user manually uploading files?

**Comment by di** [comment]
> What is the usual workflow in these cases? I would have assumed that given a release version (e.g., 1.0.0), the release would be created by their CI (uploading the files and creating the release on PyPI), and then the user would manually upload the wheels for not-supported platforms under the same (existing) 1.0.0 release version.

Possibly, but there's no reason it couldn't happen the other way around (my understanding is that for most projects like this, it's basically a race to see which build publishes first, and the behavior probably shouldn't be different depending on which happens first).

> since we only warn on API token use during release creation.

I'm thinking this should probably be on _file_ creation, instead. That way, the first upload that uses an API token will always get an email, regardless of whether it's the first file in a release, or the last. (One thing this will help protect against is a compromised API token being used to add additional, possibly malicious files to an existing release without the owners being aware).

**Comment by facutuesca** [comment]
@di I think we can close this one as completed (PR here: https://github.com/pypi/warehouse/pull/15641)
