### ISSUE TITLE
Next.js fetch package CORS error

### ISSUE THREAD

**Issue by toddcooke** [pypi/warehouse#14229]
**Describe the bug**

Calling `GET https://pypi.org/pypi/asdfasdfasdfasdfasfas/json`
results in 
```
https://pypi.org/pypi/asdfasdfasdfasdfasfas/json
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pypi.org/pypi/asdfasdfasdfasdfasfas/json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.
```

**Expected behavior**

I expect to get a 404, but not a CORS error.

**To Reproduce**

1. Create a nextjs project from this template https://vercel.com/new/clone?s=https%3A%2F%2Fgithub.com%2Fvercel%2Fvercel%2Ftree%2Fmain%2Fexamples%2Fnextjs&template=nextjs&id=67753070&b=main&showOptionalTeamCreation=false
2. Add and run this code:
```
      let resp = await fetch(`https://pypi.org/pypi/asdfasdfasdfasdfasfas/json`, {
        headers: {
          Host: "pypi.org",
          Accept: "application/json",
        },
      });
```

**My Platform**

**Additional context**

I have no issues when pypi returns 200 for a found package, it's only when it returns 404 for a non-existing package. Also I have no issues hitting pypi from the command line, only with nextjs/fetch.

**Comment by di** [comment]
I think this is probably because we try to set the appropriate CORS headers on 404 responses here:

https://github.com/pypi/warehouse/blob/97ff3692081c621c8ccc4906c6d0e228bd5225ae/warehouse/legacy/api/json.py#L193

but then we intercept all HTTP exceptions:

https://github.com/pypi/warehouse/blob/97ff3692081c621c8ccc4906c6d0e228bd5225ae/warehouse/views.py#L71-L121

And the headers are not making it through to the final response.

I think we should probably just set these headers once, in the `httpexception_view`, instead.

**Comment by miketheman** [comment]
Related #13222
