### ISSUE TITLE
Indicate that a second 2FA device must be added before the first can be removed

### ISSUE THREAD

**Issue by di** [pypi/warehouse#14233]
As a follow-up to #13771, we should make it more clear in the UI that when there is only one 2FA device on an account, a new device must be added before the existing one can be removed.

Currently the button is just disabled, with no tooltip or other message to guide the user for what to do next:

<img width="853" alt="image" src="https://github.com/pypi/warehouse/assets/294415/3afeed9f-5c9f-49ad-aaf2-afd7107aa49f">

(cc @ristomcgehee)

**Comment by songololo** [comment]
A heads-up that when trying to add another 2FA device this error message is presented:
> Account cannot be linked to more than one authentication application at a time

**Comment by di** [comment]
Ah, great point. That's only true for "Add 2FA with authentication application", because we can only support one TOTP device at a time, but we should modify the flow for that to _replace_ an existing TOTP device rather than requiring it to be deleted/recreated.

**Comment by ristomcgehee** [comment]
https://github.com/pypi/warehouse/pull/14244 will make a tooltip saying "Cannot remove last 2FA method" when you hover over the Remove button. Is that adequate for informing the user, or should we have a more visible explanation?

To support when a user needs to replace their existing TOTP device, how does this sound?
- When a user has TOTP configured, instead of the button saying "Add 2FA with authentication application", it says "Edit 2FA with authentication application".
- When the user clicks the button, the "Set up 2FA with an authentication application (TOTP)" view and the user can scan the QR code and enter a code.
- On the Account Settings page, there will still be a Remove button next to the TOTP option. If the user has no other 2FA, that button will be disabled.
- If the user has TOTP and 1 or more webauthn devices, the button will still be "Edit 2FA with authentication application".

**Comment by di** [comment]
> https://github.com/pypi/warehouse/pull/14244 will make a tooltip saying "Cannot remove last 2FA method" when you hover over the Remove button. Is that adequate for informing the user, or should we have a more visible explanation?

I think we should have a more visible explanation, probably a warning/danger banner in this section.

I think your plan for handling TOTP devices makes sense, we should probably make a separate issue to track that!

**Comment by ristomcgehee** [comment]
Added a more visible explanation in https://github.com/pypi/warehouse/pull/14258.

Created issue https://github.com/pypi/warehouse/issues/14257 for allowing editing of TOTP application.
