### ISSUE TITLE
Pypi Survey doesnot let me submit answers even after selecing the answers.

### ISSUE THREAD

**Issue by venomj26** [pypi/warehouse#14892]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by venomj26** [comment]
![image](https://github.com/pypi/warehouse/assets/44623065/1145147c-355f-4608-99ce-a9e70e0d782f)

**Comment by miketheman** [comment]
cc @riecatnor for follow up.

**Comment by riecatnor** [comment]
Hi @venomj26 - I am part of the team working on running the survey. Could you try selecting an option for the "Educational purposes" line to see if that allows you to move to the next page? I'd like to test to see if that's the issue. I am guessing you did not mark it because you do not use it for educational purposes, so I think there might be a need for an additional column for this question. I can request that change but I want to confirm that is the issue first. Thank you!

**Comment by venomj26** [comment]
What you said works for the second question. I am sorry but I perceived the second question to be which of the activity i would do primarily etc. Thanks for clarifying it. I think the issue is more with showing an error on the first question too. Is there something I am understanding wrong about the first question?

**Comment by riecatnor** [comment]
The warning at the top says "There was an error on your page." which I think is referring to the field that you left open on the second question? If you fill that field in the second question, are you able to move onto the next page? If so, then I think we may have solved it :+1:

**Comment by venomj26** [comment]
Sure ! That sounds good ! Thanks for your attention.

**Comment by miketheman** [comment]
Glad it worked out!

Closing this issue.

In general, this is the repository for tracking issues pertaining to the PyPI warehouse codebase, not the survey  😉

**Comment by venomj26** [comment]
[celebrate]     Jha, Sneha reacted to your message:
________________________________
