### ISSUE TITLE
Sending "GPG signature uploaded" email fails when using Trusted Publishing

### ISSUE THREAD

**Issue by di** [pypi/warehouse#14928]
Currently we return a 500-level failure if a user attempts to upload GPG signatures via Trusted Publishing, because we assume there is a `request.user`:

https://github.com/pypi/warehouse/blob/d5ee54d0deb193c01edf3de3243d8d2027ea0501/warehouse/forklift/legacy.py#L1144-L1146

However this might be `None` if Trusted Publishing is used, in which case the email should probably go to all owners instead.

Reported in #14927, this is https://python-software-foundation.sentry.io/share/issue/4680dcbcc9d348109307d6dc0d03f900/.

**Comment by dstufft** [comment]
FWIW we're ~5 months away from my random "well maybe May 2024? date to remove the emails/warning altogether (#13733) and ~5 months since the emails/warning were added at all.

I wouldn't feel bad if we just didn't send the email at all if `request.user` is `None`, but sending to all owners seems fine too.

**Comment by di** [comment]
This seems to happen infrequently enough that this would probably be acceptable as well!

**Comment by woodruffw** [comment]
In a peak example of "weird things breaking weird things," this 503 actually breaks twine's integration tests: https://github.com/pypa/twine/pull/1029#issuecomment-1825021758

This sufficiently surprised me while patching twine, so I'll make a quick fix here 🙂
