### ISSUE TITLE
Reject bdist uploads containing inconsistent metadata

### ISSUE THREAD

**Issue by pradyunsg** [pypi/warehouse#15884]
**What's the problem this feature will solve?**
See https://pypi.org/project/triton/0.4.0/#files, which has 0.4.1 wheel names but (as the URL indicates), the wheels are actually for a 0.4.0 version.

This happened due to an incorrectly manipulated package by the author of the package (see https://github.com/openai/triton/issues/122) which resulted in an inconsistent version number being presented between the simple index and the project page.

**Describe the solution you'd like**

Such uploads should be blocked.

**Additional context**

None? I tried to look for duplicates and couldn't find any. Apologies if I missed something relevant!

**Comment by woodruffw** [comment]
Thanks for filing! Doing a bit of triage:

It's odd that PyPI accepted this at all, since the upload endpoint _does_ check for consistency between the version in the wheel name and in the metadata:

https://github.com/pypi/warehouse/blob/7c93a28780ea728ac07b51d03a1c6b7db45899d9/warehouse/forklift/legacy.py#L1026-L1031

**Comment by woodruffw** [comment]
Oh hmm, `trition==0.4.0` was uploaded in May 2021, and that check was added just a few weeks ago with https://github.com/pypi/warehouse/pull/15795, fixing https://github.com/pypi/warehouse/issues/15749.

So I think this is already fixed 🙂

**Comment by di** [comment]
Yeah, this is fixed.
