### ISSUE TITLE
Adding SSPL to license classifiers

### ISSUE THREAD

**Issue by dsuch** [pypi/warehouse#15885]
Hello,

can you please add [SSPL](https://en.wikipedia.org/wiki/Server_Side_Public_License) to [the classifiers](https://pypi.org/classifiers/)?

It's not OSI-approved but it's still a decent open source license.

I have [a piece of software](https://pypi.org/project/zato-apitest/) licensed under it and I'm currently using "Other/Proprietary" as its license classifier because SSPL is not there even if the software is certainly open.

Thank you.

**Comment by di** [comment]
Hi, the licenses come from https://github.com/pypa/trove-classifiers/. Feel free to make a request there, although that project tends to only accept OSI-approved licenses.

Note that the [`License`](https://packaging.python.org/en/latest/specifications/core-metadata/#license) field is intended to be used for exactly this purpose, you may just want to set the license there rather than via a classifier.

**Comment by dsuch** [comment]
Thanks @di - I overlooked the "License" field. Everything is fine now. Have a great day!
