### ISSUE TITLE
The newest packages feed does not always return the latest packages

### ISSUE THREAD

**Issue by behnazh-w** [pypi/warehouse#16220]
[The newest packages feed](https://pypi.org/rss/packages.xml) might have timezone issues, which can result in returning old packages instead of the newest ones. For example, at 2024-07-03-13-31+10 I got the following result from the feed: [2024-07-03-13-31+10.zip](https://github.com/user-attachments/files/16093686/2024-07-03-13-31%2B10.zip)
containing this example timestamp for publication:
```xml
<pubDate>Wed, 03 Jul 2024 01:49:28 GMT</pubDate>
```
Later I got this feed at 2024-07-04-06-51+10: [2024-07-04-06-51+10.zip](https://github.com/user-attachments/files/16093846/2024-07-04-06-51%2B10.zip), which contained more recent packages as expected. Here is an example timestamp from this feed:
```xml
<pubDate>Wed, 03 Jul 2024 20:47:58 GMT</pubDate>
```

But then I got the following result at 2024-07-04-11-32+10: [2024-07-04-11-32+10.zip](https://github.com/user-attachments/files/16093704/2024-07-04-11-32%2B10.zip) that contains packages that are older than the ones obtained previously at 2024-07-04-06-51+10. Here is an example publication timestamp:
```xml
<pubDate>Wed, 03 Jul 2024 01:30:29 GMT</pubDate>
```

So, looks like the most recent feed contains packages that were not really the most recent.

**Comment by di** [comment]
Hi, this is not a timezone issue and is expected. This could be the case if multiple recent projects were deleted, because our feed just provides the 40 most recently packages at a given time.

https://github.com/pypi/warehouse/blob/15de75987757412a0cb38249ea60697938406c50/warehouse/rss/views.py#L87-L101

Note that similarly this feed may be missing projects if many new projects were created between multiple requests. 

Depending on what you're doing, you may want to use the XML-RPC API or the Simple API instead: https://warehouse.pypa.io/api-reference/feeds.html#project-and-release-activity-details
