### ISSUE TITLE
create documented hash/filename guarantee for hosted files

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypi/warehouse#1644]
the current explicitly undocumented scheme is 
```
hash = blake2b(FILE_CONTENT, digest_size=32)
filename = FILE_NAME
url = f"https://files.pythonhosted.org/packages/{hash[:2]}/{hash[2:4]}/{hash[4:]}/{filename}"
```
in order to more reliably use this in nixos/nixpkgs#21637 i would like to propose documenting the hashing schema possibly adding a flexibility wrt the hash in order to future-proof in case blake2b loses collision resistance

an idea could be to use something like 
```
hash_spec = "bake2b-32"
url = f"https://files.pythonhosted.org/packages-by-{hash_spec}/{hash[:2]}/{hash[2:4]}/{hash[4:]}/{filename}"
```
allowing to choose different values in future

**Comment by brainwane** [comment]
Thanks for your note and sorry for the slow response!

The folks working on Warehouse are using [limited current funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. Since this feature isn't something that the legacy site has, I've moved it to a future milestone.

Thanks and sorry again for the wait.

**Comment by miketheman** [comment]
Hey @RonnyPfannschmidt ! We're triaging older issues.

The main question is what's the exact use case for this feature?

PyPI's filename hash handling is an implementation detail, and [integrators](https://warehouse.pypa.io/api-reference/integration-guide.html#integration-guide) are meant to use the existing APIs (simple, json) or [predictable URLs scheme](https://warehouse.pypa.io/api-reference/integration-guide.html#predictable-urls) to get a redirect URL.

We'll go ahead and close this issue for now, but please reopen it with more context if needed.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the update,I'm okay with the current solution
