### ISSUE TITLE
Clickable elements in Project sidebar are easy to "mis click"

### ISSUE THREAD

**Issue by ewdurbin** [pypi/warehouse#16743]
**Describe the bug**

Project URLs in the sidebar on pages like https://pypi.org/project/django-polymorphic/ are difficult to click due to overlapping hit boxes.

For instance, when cursoring up through the list attempting to click "Homepage" here, I accidentally hit "Download":

<img width="218" alt="Screenshot 2024-09-18 at 2 26 36 PM" src="https://github.com/user-attachments/assets/ef346040-85c8-4078-a1b5-11aa831e7fc1">

Additionally, _non clickable_ things like "License" and tags act as clickable when scrolling over them:

<img width="309" alt="Screenshot 2024-09-18 at 2 32 08 PM" src="https://github.com/user-attachments/assets/ba1117c5-26d3-4399-b430-77f36c699722">

**Expected behavior**

Links should be easy to click, things that are not links should not behave as links.

**To Reproduce**

Navigate to a project page and trial/inspect the elements to see how cursor behaves and which link is active.

**My Platform**

Noticed on Safari 18.0 on MacOS 15.0.

**Additional context**

May be related to #15737 or #16532.

**Comment by di** [comment]
Looks like the "clickable"-ness is due to the `span` having the `vertical-tabs__tab` and `vertical-tabs__tab--condensed` classes, and the parent `ul` having the `vertical-tabs__list` class. Removing these will reintroduce the bullets as well, so we would need to suppress them to maintain the same view.

The spacing seems to be due to https://github.com/pypi/warehouse/blob/f3dcfcc44e2a23ef6498b5246ff47a5183f19afd/warehouse/static/sass/blocks/_verified.scss#L28

which is overridding: https://github.com/pypi/warehouse/blob/f3dcfcc44e2a23ef6498b5246ff47a5183f19afd/warehouse/static/sass/blocks/_vertical-tabs.scss#L107

However this was done so the checkboxes display inline with the link, so an alternative method to do that will need to be found.

**Comment by di** [comment]
Also, it was noted that the checkmarks may be redundant given they are already within a "verified" section, so perhaps it makes the most sense to remove them.

**Comment by ewdurbin** [comment]
I'm pretty sure the spacing/hitbox issue is _just_ the [removal of definite padding on `a` elements](https://github.com/pypi/warehouse/pull/16532/files#diff-4f148adaf67f1d00a3c38bee00dd4a6658bec9e00528940e07f003efd72b517aL33) in #16532 and I can't understand why that occurred.

**Comment by di** [comment]
Here's what it looks like with `display: inline` removed and the checkboxes removed:

<img width="295" alt="image" src="https://github.com/user-attachments/assets/de54e89f-e9a9-469c-b643-d1c2b85ef73e">

Seems like that's approximately what it originally looked like?

**Comment by di** [comment]
Here's what it looked like 4 years ago: https://web.archive.org/web/20200919103428/https://pypi.org/project/pytest-socket/

![image](https://github.com/user-attachments/assets/dfd20de4-824a-4a35-b0b3-da78aba6ff5e)

**Comment by ofek** [comment]
I'm in favor of removing the checkmarks since the entire section is under the verified header. I missed the documentation link and had to ask what the checkmarks meant because of them.
