### ISSUE TITLE
GitHub signon

### ISSUE THREAD

**Issue by KOLANICH** [pypi/warehouse#1697]
Add GitHub signon, please.

**Comment by jaddison** [comment]
I can absolutely recommend https://github.com/requests/requests-oauthlib/ for this - low dependency count, simple implementation - theoretically supports any OAuth2 provider, due to its generic and simplistic design.

**Comment by brainwane** [comment]
@KOLANICH and @jaddison, thank you for the issue and the discussion, and sorry for the slow response!

For context: The folks working on Warehouse have gotten [some limited funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap). The most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable, and so we have a better foundation for new features.

You're so not alone -- many developers want to be able to log into PyPI using GitHub for auth. [This came up on the distutils-sig mailing list](https://mail.python.org/pipermail/distutils-sig/2018-January/031901.html) and [one person](https://mail.python.org/pipermail/distutils-sig/2018-January/031858.html) recommended we look at https://python-social-auth.readthedocs.io/en/latest/ and https://github.com/uralbash/awesome-pyramid/#authentication .

But, since this feature isn't something that the legacy site has, I've moved it to [a future milestone](https://github.com/pypa/warehouse/milestone/12), to make it clear that it's something the Warehouse developers will take another look at once we've redirected traffic to the new site and shut down the old one.

Thanks and sorry again for the wait.

**Comment by KOLANICH** [comment]
Now the new site is active.

**Comment by andriyor** [comment]
Also, this can help prevent rale limit exceeded for unauthentIcated requests to Github API

**Comment by dstufft** [comment]
I'm going to close this. I don't think we're likely going to add support for any sort of federated auth like this. We had it in the past and it was painful-- while I think it's likely GitHub would be ~fine, it's better for us I believe if we "own our destiny" with regards to auth.
