### ISSUE TITLE
Assess libraries.io trending projects feed, consider replacing ours

### ISSUE THREAD

**Issue by brainwane** [pypi/warehouse#3252]
The [Libraries.io list of trending PyPI projects](https://libraries.io/trending?platforms=PyPI) is very different from the one on the http://pypi.org/ front page. Our list just computes a zscore of downloads. We should check their data & methods, and if their results are more interesting or better than ours, we should [hit their API](https://libraries.io/api) and use their list instead of ours on our front page.

From [IRC today](http://kafka.dcpython.org/day/pypa/2018-03-14).

**Comment by browniebroke** [comment]
I've looked under the hood at the [libraries.io source code](https://github.com/librariesio/libraries.io), to try to understand how their trending list was computed. However, I'm not so familiar with Ruby or Rails, so let's see what I can find... I've started by [searching for "trending"](https://github.com/librariesio/libraries.io/search?q=trending), which trimmed down the results.

At first glance, there is a query from [the repository model](https://github.com/librariesio/libraries.io/blob/94878b45ccb1dde9cb74aa3698658d29a96290a2/app/models/repository.rb#L75) which name looked promising. But the other search results from Github seem to reference [the `hacker_news` query](https://github.com/librariesio/libraries.io/blob/94878b45ccb1dde9cb74aa3698658d29a96290a2/app/models/repository.rb#L74) instead of the `trending` one. I'm not clear which query is used, but it seems it relies on Github stars? 

Now, looking at their API documentation, I'm not sure there is an endpoint available to expose this trending data. The [project search](https://libraries.io/api#project-search) seems interesting but seems to require a search term. 

Is that answering the research questions?

**Comment by brainwane** [comment]
I appreciate you looking into this, @browniebroke!

@andrew is a maintainer of Libraries.io and could probably help answer our question about the endpoint availability and how we'd access trending data.

@browniebroke could you try comparing the list of trending projects on the pypi.org front page with the list at https://libraries.io/trending?platforms=PyPI , and briefly assess how widely used or trending some of those projects seem to be (when you look for mentions of them on social media, on GitHub, in StackOverflow, and in new release announcements)? That might help us figure out how different the results are.
