### ISSUE TITLE
question: proportion of users who want to see, download package files

### ISSUE THREAD

**Issue by brainwane** [pypi/warehouse#3478]
What proportion of users particularly want to get at the package files, as a primary desideratum, when they go to a project page? We know that most users are looking at the project description and will then use `pip install` to retrieve and install package files, but some want to see the package files and checksums, and some want to see the package list and then download the files. One person writes,

>  I do want to check the downloads to see if there is a wheel or not for my platforms. I will download it for sure by hand in all cases, and in some case will build extra wheels. And I want to see the checksum too. I do not trust the code to be what it is otherwise.
> I want and I like fair control of what I am installing

Another writes:
> I never download the wheels manually, but I very often check which ones are there for a package.

From pombreda and Wooble [in IRC today](http://kafka.dcpython.org/day/pypa-dev/2018-03-30).

**Comment by njsmith** [comment]
Huh, now that I think about it, probably the main (only?) reason I visit the pypi website is to check what wheels are available and look at release dates. For "do I want to depend on this package?" questions, checking whether wheels are available is a really important clue as to how much pain I'll be causing my users if I do. And pypi is the only place to reliably check dates like "huh, so if that was deprecated in 1.7.3, how long ago was that?".

Instead of dumping raw wheel filenames at people, maybe we could present the key information visually with a little grid like:

```
         2.7   3.5   3.6
MacOS     x           x
Windows   x           x
Linux     x           x
```

I guess ideally we should surface the presence of an sdist as well, since uploading sdists is a public good and it'd be a little nudge for people to do that.

**Comment by miketheman** [comment]
Triaging older issues.

We understand that the desire here is to see what files are available for download. Work has commenced in #15087 to make the filenames more visually friendly, so will continue the issue there.
