### ISSUE TITLE
Explicit way to choose icons for Project URLs

### ISSUE THREAD

**Issue by gbdlin** [pypi/warehouse#5683]
**What's the problem this feature will solve?**
Right now, there is [logic](https://github.com/pypa/warehouse/blob/5cd92a3ecff5db2d04ba4c951830deceb34ed235/warehouse/templates/packaging/detail.html#L20-L54) that tries to guess appropriate icon for each Project URL displayed in the sidebar. There are ways to use this logic to display one of the icons included in the logic mentioned above, but this implies the use of a particular name of URL or particular URL by itself.

**Describe the solution you'd like**
There should be some additional field or method to specify `project_urls`, so there is a way to set any icon from font awesome or from a subset of it.

**Comment by di** [comment]
Thanks for the feature request! This would be quite a bit of work for a relatively small feature, since we'd need to make a modification to the core metadata specification to support additional details alongside `project_urls`. Then, we'd need to add support for this new metadata field across all projects that build, inspect, and parse this metadata (`twine`, `setuptools`, `pkg-info`, etc.)

In addition, if this existed, it would require PyPI to have a more explicit dependency on Font Awesome going forwards, and would make it hard for us to make changes in the future to PyPI's UI, and still maintain this feature.

That said, I'm inclined to say we won't likely support this, however we are willing to add new icons for specific notable domains to the existing logic if it would improve the UI.

**Comment by miketheman** [comment]
Going to close this out, since I don't think we'll be extending the metadata to support icon selection for URLs.

If there are particular URLs and icons that seem sensible, please open a pull request to add them to the logic block linked above!
