### ISSUE TITLE
Add developer version for frontend pipeline

### ISSUE THREAD

**Issue by yeraydiazdiaz** [pypi/warehouse#6141]
**What's the problem this feature will solve?**
Our current frontend pipeline generates final versions of all the artifacts every time the developer changes a file. This results in having to wait in my current setup (MacBook Pro 13" Early 2015) between 30 seconds and 1 minute on each change which greatly impacts productivity.

**Describe the solution you'd like**
A developer version of the frontend pipeline that would:

1. Only trigger the steps required for the particular change,
2. Not perform production only steps.

**Additional context**
This might be something that has less of an impact on more powerful machines I'm keen to know if other devs have experienced this as well.

**Comment by dstufft** [comment]
My 2018 MBP completes it a bit faster, but it's still noticeable.

I'm not opposed to adding something like this, but just to explain some of the rationale behind why I only added one pipeline originally. My goal was since I didn't know of a good way to test that the output of the pipeline was correct, was to at least ensure that what we're using in development would match what we're doing in production to reduce the chances of breakage.

So if we do this, it would be great if we could keep a mind to trying to keep the differences between develop and production as small as we can while achieving this goal or if someone knows of a good way to basically ensure the output in production is what someone would expect from development. Worst case scenario if there's nothing we can do, I still think it's OK to do this if it's causing pain for folks who are actually doing front end work (I'm not really one of them, so it doesn't bother me).

**Comment by yeraydiazdiaz** [comment]
@nlhkabu @di and any others working in frontend, do you think this is worth it?

It's a non trivial change and as @dstufft mentions there's some risk involved. If not I'm happy to close the issue 🙂

**Comment by di** [comment]
In my experience, this is slightly annoying, but hasn't wasted so much of my time that I felt that it needed changed. That said, I haven't been doing much of our frontend work lately.

I agree with @dstufft that the fact that our dev & prod pipelines are identical is probably a benefit here. I also suspect that there's other optimizations that could be made to improve the speed here while maintaining this benefit, but I don't have any specific examples, just a hunch.

**Comment by nlhkabu** [comment]
I would love to see this change, as it would be a big efficiency gain for me. Currently, I also experience 30 second to 1 minute delays when reloading the page after CSS changes.

My workaround is (typically) to make/experiment with changes in the browser, *then* apply them to the source files.  But even then, I still have to do a full refresh to confirm everything is working as expected.

**Comment by di** [comment]
In #7712, @nlhkabu said: 

> It would be great to improve the performance of the building of static assets in development.
> 
> Currently, when I make an update to the SCSS files, it's taking around 15 seconds to rebuild before I can refresh the page and check my work - this is very frustrating!

**Comment by di** [comment]
The main pain point here is significantly improved by #12728 (rebuilds are now nearly instantaneous). Given that, I don't think it's necessary any more to pursue a dev-only frontend pipeline. Thanks @miketheman!
