### ISSUE TITLE
Make source distributions mandatory

### ISSUE THREAD

**Issue by hrw** [pypi/warehouse#7980]
**What's the problem this feature will solve?**

Developers are now free to upload source and/or wheel files. And they do. But the problem starts when all they upload are wheel files.

Lack of source means so way to build for other Python version or other architecture/os than authors provided wheels support.

Example:

1. Project ZYX works on Py2 and Py3 and is used by project ABCD. ABCD has few supported branches: abra, cadabra, hocus. Each are in use and 'abra' supports only Py2. One day author uploads ZYX as py3 only wheel and removes all previous releases.

ABCD project users are not able to install 'abra' version anymore.

2. Project RTYU uploads newer version of their package but only as Python 3.6 wheel for manylinux1. Users of other Python versions or MS Windows or other architectures than x86 are not able to use latest version of RTYU.

**Describe the solution you'd like**

Source tarball will be always provided. So if someone needs to build wheel for their os/architecture/python_version then they always can.

**Additional context**

https://github.com/protocolbuffers/protobuf/issues/7520 is example issue.

**Comment by hrw** [comment]
https://github.com/cf-natali/ntplib/issues/1 is example of ZYX like project.

**Comment by dstufft** [comment]
I don't think that this is something we can make a decision on in he issue tracker. This would be a fairly broad policy change, and it likely is going to require a PEP to make happen. We can certainly try to do more to guide people to not publish wheel only releases, but ultimately that's currently a valid way to use PyPI if someone desires.

**Comment by nanonyme** [comment]
Is this really a real issue? Seems world did not really end when Python 2 went EOL. Something that *would* be nice to have is canonicalized repository location for project that do not keep this information in their homepage metadata. If you want to maintain something someone has end-of-life'd, best approach is most likely to pull it from source repository to patch it further, not hack with PyPI.

**Comment by hrw** [comment]
@nanonyme yes, it can be a real issue. The moment when 'pip install somepackage' returns with 'sorry, no package' while same command run on system running other architecture ends with 'somepackage vX.Y installed' is a problem.

When source is available then 'pip install somepackage' ends with fetching somepackage-vX.Y.tar.gz file, unpacking it and building. Without having to spend time on looking for project's homepage, how do they do releases (if at all), fetching source, building it by hand etc.

Especially on CI.

**Comment by hrw** [comment]
And it does not matter which arch/distro/python version it is. Some people run operating systems on x86-64 built in a way that standard binary wheels do not work.

**Comment by ewjoachim** [comment]
One could argue that publishing a package on PyPI isn't an oath to support every possible user of any system in all eternity. Even with sdists, there's no guarantee that a package is buildable in all systems, some dependencies might make it very limited in availability to some very narrowed systems.

Also, one may use a packaging lib that creates a wheel and not a sdist.

One may publish proprietary packages on PyPI and may wish to keep their sources private.

One may publish a pure-python wheel that is equivalent to a sdist and there's no reason that they would have to upload a dist too.

One could have realised they have inadvertently left a personal information in a sdist file and want to delete it (and I'm not sure we allow reuploading a sdist with a different hash in this case)

I'm seeing a lot of reasons we could have wheel-only releases, and I think Python packaging is hard enough to solve for maintainers to not add constraints. In your example, to me, it's ABCD's maintainers responsibility to either state they're not compatible with Python2 anymore or to replace XYZ with a Py2-compatible solution.

But as you stated, this happens because XYZ deleted previous releases, which is a `leftpad`-ish move considered unadvisable, with all sorts of warnings in the UI. If they did anyway, they could have removed the whole of XYZ too. A dependency repeatedly or voluntarily acting like this probably doesn't deserve that ABCD uses it if ABCD has a large user base. The problem here is unrelated to publishing sdists or not.

**Comment by aragilar** [comment]
Rather than requiring source distributions, would warning that there is no sdist uploaded (either for individual versions or for the whole package) on the package page be less of a breaking change? Developers of a package can see there is a potential issue (e.g. the example of the CI failing to upload the sdist), and potential users of a package are aware that they may be depending on a package which may not work on their systems at some point.

**Comment by di** [comment]
@aragilar I think that's probably worth exploring separately from this issue, especially since the change in #10646 makes an obvious place for such a warning.
