### ISSUE TITLE
create comments secction on PyPI

### ISSUE THREAD

**Issue by praful-potphode** [pypi/warehouse#8520]
**What's the problem this feature will solve?**
all discussions related to installations will happen in Pypi,which will become single place for all issues
**Describe the solution you'd like**

**Additional context**

**Comment by webknjaz** [comment]
This would turn PyPI into a discussion forum and an issue tracker while it's only supposed to be an index...
Also, it's a system under load, adding more dynamic apps to the backend will have a cost.

Theoretically, it could just integrate Disqus but it still feels like a feature creep for this project.

**Comment by praful-potphode** [comment]
A lot of people face issues installing libraries in python.if we can include atleast known errors and their resolutions.this would help more people adapt python.Thats why the comment section, which can be disabled also for everyone

**Comment by pradyunsg** [comment]
Is there any other package index that does this?

**Comment by dstufft** [comment]
For what it's worth, PyPI *used* to have comments for a time. They were pretty much universally hated by package authors, and caused a massive amount of strife within the community. I seem to recall several high visibility projects threatening to remove themselves from PyPI because of them. If I recall, one of the primary complaints at the time was that it provided yet another place that projects had to monitor for issues, but which had none of the power that their normal discussion forums had for triage and issue management. There might have been more complaints, it was significantly long enough ago that my memory on the specifics is very hazy.

That was a long time ago though, so it's possible that in today's world it would be better received, however before we implemented it, I would want some evidence that we've done the due diligence to go back through those old threads (they would have been on catalog-sig) and ingested the feedback people had about the system, and figure out if it would apply to a hypothetical new system, and if so is it still worth doing?

The other big question is that it is unethical to expose an open commenting system to the internet without some kind of plan for how we're going to handle moderation both in terms of the technical side of things, and how we're going to handle the increase in human effort that it would take to properly moderate these issues and ensure that all of the content is something we're OK with having on PyPI.

**Comment by ewjoachim** [comment]
That being said, there are things to explore regarding improving the visibility of issue trackers when referenced in the project. For now we have [a dedicated icon in the projects URLs](https://github.com/pypa/warehouse/blob/208c6a464fb2c68c3038349209c6bc13dc4cb5f2/warehouse/templates/packaging/detail.html#L28) but we could have more.

**Comment by dstufft** [comment]
I'm going to close this issue, and I probably should have closed it 3 years ago. There's a very low chance we add commenting to PyPI, particularly when we're already struggling to keep up with the load of moderating packages, much less comments. Add in thei historical baggage around it and it just feels like a non starter.
