### ISSUE TITLE
Add badges/info about abi3 packages forward compatibility

### ISSUE THREAD

**Issue by webknjaz** [pypi/warehouse#9066]
**What's the problem this feature will solve?**

When looking at the list of wheels in a given release of a Python package distribution, there may be a lot of files and the compat column only takes a Python version part into consideration ignoring the ABI.

**Describe the solution you'd like**

Annotate the dists with something (probably a badge, like for pre- and yanked releases) that would clearly indicate support for Python 3.x+, not just 3.x, in those wheels.

In doing so, PyPI will improve the users' understanding of what to expect from `pip install`.

**Additional context**

I realized that this info is missing from the website after seeing the confusion in these issues:
* https://github.com/pypa/gh-action-pypi-publish/issues/56
* https://github.com/pyca/cryptography/issues/5787
* https://github.com/pyca/cryptography/issues/5798

![cryptography-py36-abi3](https://user-images.githubusercontent.com/578543/107395932-92608000-6afd-11eb-967d-ad237f90b8db.png)

**Comment by di** [comment]
Since this issue was created, the release files page has changed a bit. The `cp36` column is now a flag on the release file:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/294415/184384676-9e78fe9c-e761-41fe-a369-f96e61638640.png">

I think it'd be good to turn this into one or more tags that are more explicit and human-friendly about what Python versions the artifact is compatible with.

**Comment by webknjaz** [comment]
xref #10646

**Comment by webknjaz** [comment]
xref #15606
